// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const countJobsForUser = `-- name: CountJobsForUser :one
SELECT COUNT(*) FROM jobs WHERE user_id = $1
`

func (q *Queries) CountJobsForUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countJobsForUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (
    user_id,
    status,
    input_schema,
    output_schema,
    inputs,
    prompt,
    system_prompt,
    file_blob_key,
    file_blob_size,
    file_blob_content_type,
    provider
)
VALUES ($1, 'PENDING', $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, user_id, status, input_schema, output_schema, inputs, prompt, system_prompt, file_blob_key, file_blob_size, file_blob_content_type, output, error_message, provider, attempt, created_at, updated_at, started_at, completed_at
`

type CreateJobParams struct {
	UserID              pgtype.UUID     `json:"user_id"`
	InputSchema         json.RawMessage `json:"input_schema"`
	OutputSchema        json.RawMessage `json:"output_schema"`
	Inputs              json.RawMessage `json:"inputs"`
	Prompt              string          `json:"prompt"`
	SystemPrompt        *string         `json:"system_prompt"`
	FileBlobKey         *string         `json:"file_blob_key"`
	FileBlobSize        *int64          `json:"file_blob_size"`
	FileBlobContentType *string         `json:"file_blob_content_type"`
	Provider            string          `json:"provider"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.UserID,
		arg.InputSchema,
		arg.OutputSchema,
		arg.Inputs,
		arg.Prompt,
		arg.SystemPrompt,
		arg.FileBlobKey,
		arg.FileBlobSize,
		arg.FileBlobContentType,
		arg.Provider,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.InputSchema,
		&i.OutputSchema,
		&i.Inputs,
		&i.Prompt,
		&i.SystemPrompt,
		&i.FileBlobKey,
		&i.FileBlobSize,
		&i.FileBlobContentType,
		&i.Output,
		&i.ErrorMessage,
		&i.Provider,
		&i.Attempt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getJobByID = `-- name: GetJobByID :one
SELECT id, user_id, status, input_schema, output_schema, inputs, prompt, system_prompt, file_blob_key, file_blob_size, file_blob_content_type, output, error_message, provider, attempt, created_at, updated_at, started_at, completed_at FROM jobs
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetJobByID(ctx context.Context, id pgtype.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getJobByID, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.InputSchema,
		&i.OutputSchema,
		&i.Inputs,
		&i.Prompt,
		&i.SystemPrompt,
		&i.FileBlobKey,
		&i.FileBlobSize,
		&i.FileBlobContentType,
		&i.Output,
		&i.ErrorMessage,
		&i.Provider,
		&i.Attempt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getJobByIDForUser = `-- name: GetJobByIDForUser :one
SELECT id, user_id, status, input_schema, output_schema, inputs, prompt, system_prompt, file_blob_key, file_blob_size, file_blob_content_type, output, error_message, provider, attempt, created_at, updated_at, started_at, completed_at FROM jobs
WHERE id = $1 AND user_id = $2
LIMIT 1
`

type GetJobByIDForUserParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetJobByIDForUser(ctx context.Context, arg GetJobByIDForUserParams) (Job, error) {
	row := q.db.QueryRow(ctx, getJobByIDForUser, arg.ID, arg.UserID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.InputSchema,
		&i.OutputSchema,
		&i.Inputs,
		&i.Prompt,
		&i.SystemPrompt,
		&i.FileBlobKey,
		&i.FileBlobSize,
		&i.FileBlobContentType,
		&i.Output,
		&i.ErrorMessage,
		&i.Provider,
		&i.Attempt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listJobsForUser = `-- name: ListJobsForUser :many
SELECT id, user_id, status, input_schema, output_schema, inputs, prompt, system_prompt, file_blob_key, file_blob_size, file_blob_content_type, output, error_message, provider, attempt, created_at, updated_at, started_at, completed_at FROM jobs
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListJobsForUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListJobsForUser(ctx context.Context, arg ListJobsForUserParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobsForUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.InputSchema,
			&i.OutputSchema,
			&i.Inputs,
			&i.Prompt,
			&i.SystemPrompt,
			&i.FileBlobKey,
			&i.FileBlobSize,
			&i.FileBlobContentType,
			&i.Output,
			&i.ErrorMessage,
			&i.Provider,
			&i.Attempt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markJobCompleted = `-- name: MarkJobCompleted :one
UPDATE jobs
SET status = 'COMPLETED',
    output = $2,
    completed_at = now(),
    updated_at = now(),
    error_message = NULL
WHERE id = $1
RETURNING id, user_id, status, input_schema, output_schema, inputs, prompt, system_prompt, file_blob_key, file_blob_size, file_blob_content_type, output, error_message, provider, attempt, created_at, updated_at, started_at, completed_at
`

type MarkJobCompletedParams struct {
	ID     pgtype.UUID      `json:"id"`
	Output *json.RawMessage `json:"output"`
}

func (q *Queries) MarkJobCompleted(ctx context.Context, arg MarkJobCompletedParams) (Job, error) {
	row := q.db.QueryRow(ctx, markJobCompleted, arg.ID, arg.Output)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.InputSchema,
		&i.OutputSchema,
		&i.Inputs,
		&i.Prompt,
		&i.SystemPrompt,
		&i.FileBlobKey,
		&i.FileBlobSize,
		&i.FileBlobContentType,
		&i.Output,
		&i.ErrorMessage,
		&i.Provider,
		&i.Attempt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const markJobFailed = `-- name: MarkJobFailed :one
UPDATE jobs
SET status = 'FAILED',
    error_message = $2,
    completed_at = now(),
    updated_at = now()
WHERE id = $1
RETURNING id, user_id, status, input_schema, output_schema, inputs, prompt, system_prompt, file_blob_key, file_blob_size, file_blob_content_type, output, error_message, provider, attempt, created_at, updated_at, started_at, completed_at
`

type MarkJobFailedParams struct {
	ID           pgtype.UUID `json:"id"`
	ErrorMessage *string     `json:"error_message"`
}

func (q *Queries) MarkJobFailed(ctx context.Context, arg MarkJobFailedParams) (Job, error) {
	row := q.db.QueryRow(ctx, markJobFailed, arg.ID, arg.ErrorMessage)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.InputSchema,
		&i.OutputSchema,
		&i.Inputs,
		&i.Prompt,
		&i.SystemPrompt,
		&i.FileBlobKey,
		&i.FileBlobSize,
		&i.FileBlobContentType,
		&i.Output,
		&i.ErrorMessage,
		&i.Provider,
		&i.Attempt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const markJobProcessing = `-- name: MarkJobProcessing :one
UPDATE jobs
SET status = 'PROCESSING',
    started_at = now(),
    updated_at = now(),
    attempt = attempt + 1
WHERE id = $1
RETURNING id, user_id, status, input_schema, output_schema, inputs, prompt, system_prompt, file_blob_key, file_blob_size, file_blob_content_type, output, error_message, provider, attempt, created_at, updated_at, started_at, completed_at
`

func (q *Queries) MarkJobProcessing(ctx context.Context, id pgtype.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, markJobProcessing, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.InputSchema,
		&i.OutputSchema,
		&i.Inputs,
		&i.Prompt,
		&i.SystemPrompt,
		&i.FileBlobKey,
		&i.FileBlobSize,
		&i.FileBlobContentType,
		&i.Output,
		&i.ErrorMessage,
		&i.Provider,
		&i.Attempt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}
