// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type Job struct {
	ID                  pgtype.UUID        `json:"id"`
	UserID              pgtype.UUID        `json:"user_id"`
	Status              string             `json:"status"`
	InputSchema         json.RawMessage    `json:"input_schema"`
	OutputSchema        json.RawMessage    `json:"output_schema"`
	Inputs              json.RawMessage    `json:"inputs"`
	Prompt              string             `json:"prompt"`
	SystemPrompt        *string            `json:"system_prompt"`
	FileBlobKey         *string            `json:"file_blob_key"`
	FileBlobSize        *int64             `json:"file_blob_size"`
	FileBlobContentType *string            `json:"file_blob_content_type"`
	Output              *json.RawMessage   `json:"output"`
	ErrorMessage        *string            `json:"error_message"`
	Provider            string             `json:"provider"`
	Attempt             int32              `json:"attempt"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	StartedAt           pgtype.Timestamptz `json:"started_at"`
	CompletedAt         pgtype.Timestamptz `json:"completed_at"`
}

type Session struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
