root = "/src"
tmp_dir = "tmp"

[build]
  cmd = "go build -buildvcs=false -o /tmp/consumers ./apps/consumers"
  bin = "/tmp/consumers"
  include_ext = ["go"]
  exclude_dir = ["tmp", "apps/web", "node_modules", "docs"]
  delay = 500

[log]
  time = true
